### ISSUE TITLE
Processing ultima genomics single end data

### ISSUE THREAD

**Issue by raysinensis** [rnabioco/scraps#74]
While the sequencer is poor in dealing with homopolymers (and suffers in the immediate flanking 3-5nt as well), the single end sequencing data after reading through poly(dT) has been shown to be able to align via cellranger.
[Single Cell RNA-seq App Note_P00029_Rev B.pdf](https://github.com/rnabioco/scraps/files/12548496/Single.Cell.RNA-seq.App.Note_P00029_Rev.B.pdf)

**Comment by raysinensis** [comment]
https://github.com/rnabioco/scraps/tree/ultima_singleend

**Comment by agillen** [comment]
Closed with 1f0356fecba0d024901236191c4d1b8d431b7944, which added Ultima Genomics (and generic R1-only support).
